name: CI
on: [push, pull_request]
jobs:
   build:
        runs-on: ubuntu-late
         strategy:
            matrix:
                node-version: [12.x, 14.x]
        steps:
             - run: npm install
              - run: npm run test